CREATE DATABASE Deso9_LuyenHaiDang
USE Deso9_LuyenHaiDang
--T?o c? s? d? li?u--
--T?o b?ng l?p h?c--
CREATE TABLE Class
(
IDCLASS CHAR(10),
NAMECLASS NVARCHAR(50) UNIQUE,
NUMBERSTUDENT INT,
CONSTRAINT PK_CLASS PRIMARY KEY(IDCLASS)
)
--T?o b?ng sinh viên--
CREATE TABLE Student
(
IDSTUDENT CHAR(10),
NAMESTUDENT NVARCHAR(30),
BIRTHDAY DATE CHECK(YEAR(BIRTHDAY)<=1995 AND YEAR(BIRTHDAY)>=1990),
SEX NVARCHAR(3) CHECK(SEX IN (N'Nam',N'N?')),
ANDRESS NVARCHAR(30),
NUMBERPHONE NVARCHAR(10),
EMAIL NVARCHAR(30),
IDCLASS CHAR(10) FOREIGN KEY REFERENCES CLASS(IDCLASS) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PK_STUDENT PRIMARY KEY(IDSTUDENT)
)
--T?o b?ng giáo viên--
CREATE TABLE Teacher
(
IDTEACHER CHAR(10),
NAMETEACHER NVARCHAR(30),
BIRTHDAY DATE CHECK(YEAR(BIRTHDAY)<=1995 AND YEAR(BIRTHDAY)>=1990),
SEX NVARCHAR(3) CHECK(SEX IN (N'Nam',N'N?')),
ANDRESS NVARCHAR(30),
NUMBERPHONE NVARCHAR(10),
EMAIL NVARCHAR(30),
CONSTRAINT PK_TEACHER PRIMARY KEY(IDTEACHER)
)
--T?o b?ng môn h?c--
CREATE TABLE Subject
(
IDSUBJECT CHAR(10),
NAMESUBJECT NVARCHAR(30),
NUMBERCREDITS INT CHECK(NUMBERCREDITS > 0 AND NUMBERCREDITS < 16)
CONSTRAINT PK_SUBJECT PRIMARY KEY(IDSUBJECT)
)